Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/bionic64'

  config.vm.provision 'shell',
                      reboot: true,
                      inline: 'echo BRFORE_REBOOT'

  config.vm.provision 'shell',
                      inline: 'echo AFTER_REBOOT'
end
